package got.client.render;

import cpw.mods.fml.client.registry.RenderingRegistry;
import got.client.effect.GOTEntityAlignmentBonus;
import got.client.render.animal.*;
import got.client.render.npc.*;
import got.client.render.other.*;
import got.common.database.GOTRegistry;
import got.common.entity.animal.*;
import got.common.entity.dragon.GOTEntityDragon;
import got.common.entity.essos.*;
import got.common.entity.essos.asshai.*;
import got.common.entity.essos.braavos.GOTEntityBraavosMan;
import got.common.entity.essos.dothraki.GOTEntityDothraki;
import got.common.entity.essos.ghiscar.*;
import got.common.entity.essos.gold.GOTEntityGoldenMan;
import got.common.entity.essos.ibben.GOTEntityIbbenMan;
import got.common.entity.essos.jogos.GOTEntityJogos;
import got.common.entity.essos.legendary.GOTEntityMissandei;
import got.common.entity.essos.legendary.captain.GOTEntityHarryStrickland;
import got.common.entity.essos.legendary.captain.GOTEntityKraznysMoNakloz;
import got.common.entity.essos.legendary.captain.GOTEntitySalladhorSaan;
import got.common.entity.essos.legendary.quest.*;
import got.common.entity.essos.legendary.trader.*;
import got.common.entity.essos.legendary.warrior.*;
import got.common.entity.essos.lhazar.GOTEntityLhazarMan;
import got.common.entity.essos.lorath.GOTEntityLorathMan;
import got.common.entity.essos.lys.*;
import got.common.entity.essos.mossovy.*;
import got.common.entity.essos.myr.*;
import got.common.entity.essos.norvos.GOTEntityNorvosMan;
import got.common.entity.essos.pentos.GOTEntityPentosMan;
import got.common.entity.essos.qarth.*;
import got.common.entity.essos.qohor.*;
import got.common.entity.essos.tyrosh.*;
import got.common.entity.essos.volantis.*;
import got.common.entity.essos.yiti.GOTEntityYiTiMan;
import got.common.entity.other.*;
import got.common.entity.sothoryos.sothoryos.GOTEntitySothoryosMan;
import got.common.entity.sothoryos.summer.GOTEntitySummerMan;
import got.common.entity.westeros.*;
import got.common.entity.westeros.arryn.GOTEntityArrynMan;
import got.common.entity.westeros.crownlands.*;
import got.common.entity.westeros.dorne.GOTEntityDorneMan;
import got.common.entity.westeros.dragonstone.GOTEntityDragonstoneMan;
import got.common.entity.westeros.gift.GOTEntityGiftMan;
import got.common.entity.westeros.hillmen.*;
import got.common.entity.westeros.ice.*;
import got.common.entity.westeros.ironborn.GOTEntityIronbornMan;
import got.common.entity.westeros.legendary.captain.*;
import got.common.entity.westeros.legendary.deco.*;
import got.common.entity.westeros.legendary.quest.*;
import got.common.entity.westeros.legendary.reborn.*;
import got.common.entity.westeros.legendary.trader.*;
import got.common.entity.westeros.legendary.warrior.*;
import got.common.entity.westeros.north.GOTEntityNorthMan;
import got.common.entity.westeros.north.hillmen.*;
import got.common.entity.westeros.reach.GOTEntityReachMan;
import got.common.entity.westeros.riverlands.GOTEntityRiverlandsMan;
import got.common.entity.westeros.stormlands.GOTEntityStormlandsMan;
import got.common.entity.westeros.targaryen.GOTEntityTargaryenMan;
import got.common.entity.westeros.westerlands.GOTEntityWesterlandsMan;
import got.common.entity.westeros.wildling.*;
import got.common.entity.westeros.wildling.thenn.*;
import net.minecraft.client.renderer.entity.RenderSnowball;
import net.minecraft.entity.projectile.EntityPotion;
import net.minecraft.init.Items;

public class GOTRender {
	public static void renderFactionNPC() {
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityArrynMan.class, new GOTRenderFactionNPC("westeros/westeros"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityAsshaiMan.class, new GOTRenderFactionNPC("essos/asshai"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityBraavosMan.class, new GOTRenderFactionNPC("essos/lite"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityCrasterWife.class, new GOTRenderFactionNPC("westeros/wild"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityCrownlandsMan.class, new GOTRenderFactionNPC("westeros/westeros"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityDorneMan.class, new GOTRenderFactionNPC("essos/dark"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityDothraki.class, new GOTRenderFactionNPC("essos/nomad"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityDragonstoneMan.class, new GOTRenderFactionNPC("westeros/westeros"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityGhiscarMan.class, new GOTRenderFactionNPC("essos/dark"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityGhiscarSlave.class, new GOTRenderFactionNPC("essos/slave"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityGiftMan.class, new GOTRenderFactionNPC("westeros/gift"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityGoldenMan.class, new GOTRenderFactionNPC("essos/lite"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityHillman.class, new GOTRenderFactionNPCLayered("westeros/wild"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityHillmanWarrior.class, new GOTRenderFactionNPC("westeros/wild"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityIronbornMan.class, new GOTRenderFactionNPC("westeros/ironborn"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityJogos.class, new GOTRenderFactionNPC("essos/jogos", 0.9f));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityLhazarMan.class, new GOTRenderFactionNPC("essos/nomad"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityLorathMan.class, new GOTRenderFactionNPC("essos/lite"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityLysMan.class, new GOTRenderFactionNPC("essos/dark"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityLysSlave.class, new GOTRenderFactionNPC("essos/slave"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityMyrMan.class, new GOTRenderFactionNPC("essos/lite"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityMyrSlave.class, new GOTRenderFactionNPC("essos/slave"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityNorthHillman.class, new GOTRenderFactionNPCLayered("westeros/wild"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityNorthHillmanWarrior.class, new GOTRenderFactionNPC("westeros/wild"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityNorthMan.class, new GOTRenderFactionNPC("westeros/north"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityNorvosMan.class, new GOTRenderFactionNPC("essos/lite"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityPentosMan.class, new GOTRenderFactionNPC("essos/lite"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityQarthMan.class, new GOTRenderFactionNPC("essos/lite"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityQohorMan.class, new GOTRenderFactionNPC("essos/lite"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityReachMan.class, new GOTRenderFactionNPC("westeros/westeros"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityRiverlandsMan.class, new GOTRenderFactionNPC("westeros/westeros"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntitySothoryosMan.class, new GOTRenderFactionNPC("sothoryos/sothoryos"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityStormlandsMan.class, new GOTRenderFactionNPC("westeros/westeros"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntitySummerMan.class, new GOTRenderFactionNPC("sothoryos/summer"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityTargaryenMan.class, new GOTRenderFactionNPC("westeros/westeros"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityThenn.class, new GOTRenderFactionNPC("westeros/thenn"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityTyroshMan.class, new GOTRenderFactionNPC("essos/dark"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityTyroshSlave.class, new GOTRenderFactionNPC("essos/slave"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityVolantisMan.class, new GOTRenderFactionNPC("essos/lite"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityVolantisSlave.class, new GOTRenderFactionNPC("essos/slave"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityWesterlandsMan.class, new GOTRenderFactionNPC("westeros/westeros"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityWildling.class, new GOTRenderFactionNPC("westeros/wild"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityYiTiMan.class, new GOTRenderFactionNPC("essos/yiti"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityWight.class, new GOTRenderFactionNPC("westeros/ice/wight"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityIbbenMan.class, new GOTRenderFactionNPCLayered("westeros/wild"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityIfekevron.class, new GOTRenderFactionNPCLayered("essos/wild"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityMercenary.class, new GOTRenderFactionNPCLayered("westeros/westeros"));
	}

	public static void renderLegendaryNPC() {
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityAemonTargaryen.class, new GOTRenderLegendaryNPC("aemon"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityAsshaiArchmag.class, new GOTRenderLegendaryNPC("archmag"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityBericDayne.class, new GOTRenderLegendaryNPC("beric_dayne"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityCerseiLannister.class, new GOTRenderLegendaryNPC("cersei_lannister"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityDaenerysTargaryen.class, new GOTRenderLegendaryNPC("daenerys_targaryen"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityGeroldDayne.class, new GOTRenderLegendaryNPC("gerold_dayne"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityHodor.class, new GOTRenderLegendaryNPC("hodor", 1.3f));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityHummel009.class, new GOTRenderLegendaryNPC("hummel009"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityJaqenHghar.class, new GOTRenderLegendaryNPC("jaqen_hghar"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityJorahMormont.class, new GOTRenderLegendaryNPC("jorah_mormont"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityKevanLannister.class, new GOTRenderLegendaryNPC("kevan_lannister"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityKitraJuvain.class, new GOTRenderLegendaryNPC("kitra_juvain"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityLorasTyrell.class, new GOTRenderLegendaryNPC("loras_tyrell"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityMelisandra.class, new GOTRenderLegendaryNPC("melisandra"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityNightKing.class, new GOTRenderLegendaryNPC("night_king", 1.1f));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityOberynMartell.class, new GOTRenderLegendaryNPC("oberyn_martell"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityPetyrBaelish.class, new GOTRenderLegendaryNPC("petyr_baelish"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityPycelle.class, new GOTRenderLegendaryNPC("pycelle"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityRamsayBolton.class, new GOTRenderLegendaryNPC("ramsay_bolton"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityRenlyBaratheon.class, new GOTRenderLegendaryNPC("renly_baratheon"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityStannisBaratheon.class, new GOTRenderLegendaryNPC("stannis_baratheon"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityTobhoMott.class, new GOTRenderLegendaryNPC("tobho_mott"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityTywinLannister.class, new GOTRenderLegendaryNPC("tywin_lannister"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityVarys.class, new GOTRenderLegendaryNPC("varys"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityWalderFrey.class, new GOTRenderLegendaryNPC("walder_frey"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityYohnRoyce.class, new GOTRenderLegendaryNPC("yohn_royce"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityBarristanSelmy.class, new GOTRenderLegendaryNPC("barristan_selmy"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityGendryBaratheon.class, new GOTRenderLegendaryNPC("gendry_baratheon"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityDoranMartell.class, new GOTRenderLegendaryNPC("doran_martell"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntitySansaStark.class, new GOTRenderLegendaryNPC("sansa_stark"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityYgritte.class, new GOTRenderLegendaryNPC("ygritte"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityEbrose.class, new GOTRenderLegendaryNPC("ebrose"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityMargaeryTyrell.class, new GOTRenderLegendaryNPC("margaery_tyrell"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityEllaryaSand.class, new GOTRenderLegendaryNPC("ellarya_sand"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityBryndenTully.class, new GOTRenderLegendaryNPC("brynden_tully"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityArdrianCeltigar.class, new GOTRenderLegendaryNPC("ardrian_celtigar"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityAddamMarbrand.class, new GOTRenderLegendaryNPC("addam_marbrand"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityAndersYronwood.class, new GOTRenderLegendaryNPC("anders_yronwood"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityHarroldHardyng.class, new GOTRenderLegendaryNPC("harrold_hardyng"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityDunstanDrumm.class, new GOTRenderLegendaryNPC("dunstan_drumm"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityGarlanTyrell.class, new GOTRenderLegendaryNPC("garlan_tyrell"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityWillasTyrell.class, new GOTRenderLegendaryNPC("willas_tyrell"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityMonfordVelaryon.class, new GOTRenderLegendaryNPC("monford_velaryon"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityAuraneWaters.class, new GOTRenderLegendaryNPC("aurane_waters"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityForleyPrester.class, new GOTRenderLegendaryNPC("forley_prester"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityTytosBlackwood.class, new GOTRenderLegendaryNPC("tytos_blackwood"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityHarrasHarlaw.class, new GOTRenderLegendaryNPC("harras_harlaw"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityHarysSwyft.class, new GOTRenderLegendaryNPC("harys_swyft"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityHortonRedfort.class, new GOTRenderLegendaryNPC("horton_redfort"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityJonosBracken.class, new GOTRenderLegendaryNPC("jonos_bracken"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityLeoLefford.class, new GOTRenderLegendaryNPC("leo_lefford"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityLeytonHightower.class, new GOTRenderLegendaryNPC("leyton_hightower"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityLyleCrakehall.class, new GOTRenderLegendaryNPC("lyle_crakehall"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityLynCorbray.class, new GOTRenderLegendaryNPC("lyn_corbray"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityMathisRowan.class, new GOTRenderLegendaryNPC("mathis_rowan"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityPaxterRedwyne.class, new GOTRenderLegendaryNPC("paxter_redwyne"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityQuennRoxton.class, new GOTRenderLegendaryNPC("quenn_roxton"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityQuentenBanefort.class, new GOTRenderLegendaryNPC("quenten_banefort"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityRandyllTarly.class, new GOTRenderLegendaryNPC("randyll_tarly"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityRodrikHarlaw.class, new GOTRenderLegendaryNPC("rodrik_harlaw"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntitySebastonFarman.class, new GOTRenderLegendaryNPC("sebaston_farman"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntitySelwynTarth.class, new GOTRenderLegendaryNPC("selwyn_tarth"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityTytosBrax.class, new GOTRenderLegendaryNPC("tytos_brax"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityBronn.class, new GOTRenderLegendaryNPC("bronn"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityMullin.class, new GOTRenderLegendaryNPC("mullin"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityIlynPayne.class, new GOTRenderLegendaryNPC("ilyn_payne"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityJanosSlynt.class, new GOTRenderLegendaryNPC("janos_slynt"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityPodrickPayne.class, new GOTRenderLegendaryNPC("podrick_payne"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityHosterTully.class, new GOTRenderLegendaryNPC("hoster_tully"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityOlennaTyrell.class, new GOTRenderLegendaryNPC("olenna_tyrell"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityAryaStark.class, new GOTRenderLegendaryNPC("arya_stark", 0.75f));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityThreeEyedRaven.class, new GOTRenderLegendaryNPC("three_eyed_raven"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityAeronGreyjoy.class, new GOTRenderLegendaryNPC("aeron_greyjoy"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityAreoHotah.class, new GOTRenderLegendaryNPC("areo_hotah", 1.2f));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityBlackWalderFrey.class, new GOTRenderLegendaryNPC("black_walder_frey"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityLotharFrey.class, new GOTRenderLegendaryNPC("lothar_frey"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityBranStark.class, new GOTRenderLegendaryNPC("bran_stark", 0.75f));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityRickonStark.class, new GOTRenderLegendaryNPC("rickon_stark", 0.65f));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityDaarioNaharis.class, new GOTRenderLegendaryNPC("daario_naharis"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityGeroldGrafton.class, new GOTRenderLegendaryNPC("gerold_grafton"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityHizdahrZoLoraq.class, new GOTRenderLegendaryNPC("hizdahr_zo_loraq"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityLuwin.class, new GOTRenderLegendaryNPC("luwin"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityQyburn.class, new GOTRenderLegendaryNPC("qyburn"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityRodrikCassel.class, new GOTRenderLegendaryNPC("rodrik_cassel"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityTrystaneMartell.class, new GOTRenderLegendaryNPC("trystane_martell", 0.9f));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityTommenBaratheon.class, new GOTRenderLegendaryNPC("tommen_baratheon", 0.75f));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityShireenBaratheon.class, new GOTRenderLegendaryNPC("shireen_baratheon", 0.75f));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntitySelyseBaratheon.class, new GOTRenderLegendaryNPC("selyse_baratheon"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityMyrcellaBaratheon.class, new GOTRenderLegendaryNPC("myrcella_baratheon", 0.9f));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityMissandei.class, new GOTRenderLegendaryNPC("missandei"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityRobinArryn.class, new GOTRenderLegendaryNPC("robin_arryn", 0.75f));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityLysaArryn.class, new GOTRenderLegendaryNPC("lysa_arryn"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityCatelynStark.class, new GOTRenderLegendaryNPC("catelyn_stark"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityDavenLannister.class, new GOTRenderLegendaryNPC("daven_lannister"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityHarmune.class, new GOTRenderLegendaryNPC("harmune"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityGreyWorm.class, new GOTRenderLegendaryNPC("grey_worm"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityRazdalMoEraz.class, new GOTRenderLegendaryNPC("razdal_mo_eraz"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityArianneMartell.class, new GOTRenderLegendaryNPC("arianne_martell"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityManfreyMartell.class, new GOTRenderLegendaryNPC("manfrey_martell"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityMerynTrant.class, new GOTRenderLegendaryNPC("meryn_trant"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityQuentynMartell.class, new GOTRenderLegendaryNPC("quentyn_martell"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityShae.class, new GOTRenderLegendaryNPC("shae"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityMellario.class, new GOTRenderLegendaryNPC("mellario"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityAmoryLorch.class, new GOTRenderLegendaryNPC("amory_lorch"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityDagmer.class, new GOTRenderLegendaryNPC("dagmer"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityPolliver.class, new GOTRenderLegendaryNPC("polliver"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntitySalladhorSaan.class, new GOTRenderLegendaryNPC("salladhor_saan"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityVargoHoat.class, new GOTRenderLegendaryNPC("vargo_hoat"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityYoren.class, new GOTRenderLegendaryNPC("yoren"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityTychoNestoris.class, new GOTRenderLegendaryNPC("tycho_nestoris"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityAnyaWaynwood.class, new GOTRenderLegendaryNPC("anya_waynwood"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityClementPiper.class, new GOTRenderLegendaryNPC("clement_piper"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityGilwoodHunter.class, new GOTRenderLegendaryNPC("gilwood_hunter"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityHelmanTallhart.class, new GOTRenderLegendaryNPC("helman_tallhart"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityJasonMallister.class, new GOTRenderLegendaryNPC("jason_mallister"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityOrtonMerryweather.class, new GOTRenderLegendaryNPC("orton_merryweather"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntitySymondTempleton.class, new GOTRenderLegendaryNPC("symond_templeton"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityAndrikTheUnsmilling.class, new GOTRenderLegendaryNPC("andrik_the_unsmilling"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityBaelorBlacktyde.class, new GOTRenderLegendaryNPC("baelor_blacktyde"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityBarbreyDustin.class, new GOTRenderLegendaryNPC("barbrey_dustin"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityCleyCerwyn.class, new GOTRenderLegendaryNPC("cley_cerwyn"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityEldonEstermont.class, new GOTRenderLegendaryNPC("eldon_estermont"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityErikIronmaker.class, new GOTRenderLegendaryNPC("erik_ironmaker"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityFranklynFowler.class, new GOTRenderLegendaryNPC("franklyn_fowler"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityGoroldGoodbrother.class, new GOTRenderLegendaryNPC("gorold_goodbrother"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityGulianSwann.class, new GOTRenderLegendaryNPC("gulian_swann"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityGylbertFarwynd.class, new GOTRenderLegendaryNPC("gylbert_farwynd"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityHarmenUller.class, new GOTRenderLegendaryNPC("harmen_uller"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityJonConnington.class, new GOTRenderLegendaryNPC("jon_connington"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityMaronVolmark.class, new GOTRenderLegendaryNPC("maron_volmark"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityQuentynQorgyle.class, new GOTRenderLegendaryNPC("quentyn_qorgyle"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityRodrikRyswell.class, new GOTRenderLegendaryNPC("rodrik_ryswell"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityWilliamMooton.class, new GOTRenderLegendaryNPC("william_mooton"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityYoungGriff.class, new GOTRenderLegendaryNPC("young_griff", 0.9f));
	}

	public static void renderLegendaryNPCLayered() {
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityAlliserThorne.class, new GOTRenderLegendaryNPCLayered("alliser_thorne"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityBalonGreyjoy.class, new GOTRenderLegendaryNPCLayered("balon_greyjoy"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityBericDondarrion.class, new GOTRenderLegendaryNPCLayered("beric_dondarrion"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityBuGai.class, new GOTRenderLegendaryNPCLayered("bu_gai"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityCotterPyke.class, new GOTRenderLegendaryNPCLayered("cotter_pyke"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityCraster.class, new GOTRenderLegendaryNPCLayered("craster"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityDavosSeaworth.class, new GOTRenderLegendaryNPCLayered("davos_seaworth"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityDenysMallister.class, new GOTRenderLegendaryNPCLayered("denys_mallister"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityEuronGreyjoy.class, new GOTRenderLegendaryNPCLayered("euron_greyjoy"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityHowlandReed.class, new GOTRenderLegendaryNPCLayered("howland_reed"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityJaimeLannister.class, new GOTRenderLegendaryNPCLayered("jaime_lannister"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityJeorMormont.class, new GOTRenderLegendaryNPCLayered("jeor_mormont"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityJoffreyBaratheon.class, new GOTRenderLegendaryNPCLayered("joffrey_baratheon", 0.9f));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityJohnUmber.class, new GOTRenderLegendaryNPCLayered("john_umber", 1.2f));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityJonSnow.Stage1.class, new GOTRenderLegendaryNPCLayered("jon_snow"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityJonSnow.Stage2.class, new GOTRenderLegendaryNPCLayered("jon_snow_north"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityRickardKarstark.class, new GOTRenderLegendaryNPCLayered("rickard_karstark"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityRobbStark.class, new GOTRenderLegendaryNPCLayered("robb_stark"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityRooseBolton.class, new GOTRenderLegendaryNPCLayered("roose_bolton"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntitySandorClegane.class, new GOTRenderLegendaryNPCLayered("sandor_clegane", 1.2f));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityVictarionGreyjoy.class, new GOTRenderLegendaryNPCLayered("victarion_greyjoy", true));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityWymanManderly.class, new GOTRenderLegendaryNPCLayered("wyman_manderly"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityYaraGreyjoy.class, new GOTRenderLegendaryNPCLayered("yara_greyjoy"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityThoros.class, new GOTRenderLegendaryNPCLayered("thoros"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityXaroXhoanDaxos.class, new GOTRenderLegendaryNPCLayered("xaro_xhoan_daxos"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityIllyrioMopatis.class, new GOTRenderLegendaryNPCLayered("illyrio_mopatis"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityBenjenStark.class, new GOTRenderLegendaryNPCLayered("benjen_stark"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityBrienneTarth.class, new GOTRenderLegendaryNPCLayered("brienne_tarth", 1.2f));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityTormund.class, new GOTRenderLegendaryNPCLayered("tormund"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityManceRayder.class, new GOTRenderLegendaryNPCLayered("mance_rayder"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityMaceTyrell.class, new GOTRenderLegendaryNPCLayered("mace_tyrell"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityEdmureTully.class, new GOTRenderLegendaryNPCLayered("edmure_tully"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityKraznysMoNakloz.class, new GOTRenderLegendaryNPCLayered("kraznys_mo_nakloz"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityHighSepton.class, new GOTRenderLegendaryNPCLayered("high_septon"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityEdd.class, new GOTRenderLegendaryNPCLayered("edd"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityMaegeMormont.class, new GOTRenderLegendaryNPCLayered("maege_mormont"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntitySamwellTarly.class, new GOTRenderLegendaryNPCLayered("samwell_tarly"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityOsha.class, new GOTRenderLegendaryNPCLayered("osha"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityHotPie.class, new GOTRenderLegendaryNPCLayered("hot_pie", 0.9f));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityMatthosSeaworth.class, new GOTRenderLegendaryNPCLayered("matthos_seaworth"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityMoqorro.class, new GOTRenderLegendaryNPCLayered("moqorro"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityHarryStrickland.class, new GOTRenderLegendaryNPCLayered("harry_strickland"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityBenedarBelmore.class, new GOTRenderLegendaryNPCLayered("benedar_belmore"));
	}

	public static void renderMonofolderNPC() {
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityThief.class, new GOTRenderFactionNPCMonofolder("westeros/bandit"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityBandit.class, new GOTRenderFactionNPCMonofolder("westeros/bandit"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityEssosBandit.class, new GOTRenderFactionNPCMonofolder("essos/bandit"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityGhiscarUnsullied.class, new GOTRenderFactionNPCMonofolder("essos/unsullied"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityMaester.class, new GOTRenderFactionNPCMonofolder("westeros/maester"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityMossovyWitcher.class, new GOTRenderFactionNPCMonofolder("essos/asshai/male"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityQohorUnsullied.class, new GOTRenderFactionNPCMonofolder("essos/unsullied"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityScrapTrader.class, new GOTRenderFactionNPCMonofolder("westeros/scrap"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityStoneman.class, new GOTRenderFactionNPCMonofolder("essos/stone"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityThennBerserker.class, new GOTRenderFactionNPCMonofolder("westeros/thenn/male", 1.1f));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityWhiteWalker.class, new GOTRenderFactionNPCMonofolder("westeros/ice/walker"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityWhore.class, new GOTRenderFactionNPCMonofolder("westeros/whore"));
	}

	public static void renderMonotextureNPC() {
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityAsshaiAlchemist.class, new GOTRenderFactionNPCMonotexture("essos/alchemist"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityAsshaiShadowbinder.class, new GOTRenderFactionNPCMonotexture("essos/alchemist"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityCrownlandsAlchemist.class, new GOTRenderFactionNPCMonotexture("westeros/alchemist"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityQarthWarlock.class, new GOTRenderFactionNPCMonotexture("essos/pree"));
	}

	public static void renderOther() {
		RenderingRegistry.registerEntityRenderingHandler(EntityPotion.class, new RenderSnowball(Items.potionitem, 16384));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityAlignmentBonus.class, new GOTRenderAlignmentBonus());
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityArrowPoisoned.class, new GOTRenderArrowPoisoned());
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityArrowFire.class, new GOTRenderArrowFire());
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityAurochs.class, new GOTRenderAurochs());
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityBanner.class, new GOTRenderBanner());
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityBannerWall.class, new GOTRenderBannerWall());
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityBarrel.class, new GOTRenderBarrel());
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityBarrowWight.class, new GOTRenderBarrowWight());
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityBear.class, new GOTRenderBear());
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityBearRug.class, new GOTRenderBearRug());
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityBird.class, new GOTRenderBird());
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityBomb.class, new GOTRenderBomb());
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityButterfly.class, new GOTRenderButterfly());
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityCamel.class, new GOTRenderCamel());
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityCargocart.class, new GOTRenderCargocart());
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityConker.class, new RenderSnowball(GOTRegistry.chestnut));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityCrocodile.class, new GOTRenderCrocodile());
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityCrossbowBolt.class, new GOTRenderCrossbowBolt());
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityDart.class, new GOTRenderDart());
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityDeer.class, new GOTRenderDeer());
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityDikDik.class, new GOTRenderDikDik());
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityDirewolf.class, new GOTRenderDirewolf());
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityDragon.class, new GOTRenderDragon());
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityElephant.class, new GOTRenderElephant());
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityFallingFireJar.class, new GOTRenderFallingFireJar());
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityFallingTreasure.class, new GOTRenderFallingCoinPile());
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityFirePot.class, new RenderSnowball(GOTRegistry.firePot));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityFish.class, new GOTRenderFish());
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityFlamingo.class, new GOTRenderFlamingo());
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityGemsbok.class, new GOTRenderGemsbok());
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityGiant.class, new GOTRenderGiant("giant"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityGiraffe.class, new GOTRenderGiraffe());
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityGiraffeRug.class, new GOTRenderGiraffeRug());
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityGregorClegane.Alive.class, new GOTRenderGregorClegane.Alive());
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityGregorClegane.Dead.class, new GOTRenderGregorClegane.Dead());
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityHorse.class, new GOTRenderHorse());
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityIceSpider.class, new GOTRenderIceSpider());
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityInvasionSpawner.class, new GOTRenderInvasionSpawner());
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityKineAraw.class, new GOTRenderKineAraw());
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityLancelLannister.Normal.class, new GOTRenderLancelLannister.Normal());
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityLancelLannister.Religious.class, new GOTRenderLancelLannister.Religious());
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityLingeringEffect.class, new GOTRenderLingeringEffect());
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityLingeringPotion.class, new GOTRenderLingeringPotion());
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityLionBase.class, new GOTRenderLion());
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityLionRug.class, new GOTRenderLionRug());
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityMammoth.class, new GOTRenderMammoth());
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityManticore.class, new GOTRenderManticore());
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityMidges.class, new GOTRenderMidges());
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityMossovyWerewolf.class, new GOTRenderMossovyWerewolf());
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityMysteryWeb.class, new RenderSnowball(GOTRegistry.mysteryWeb));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityNPCRespawner.class, new GOTRenderNPCRespawner());
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityPebble.class, new RenderSnowball(GOTRegistry.pebble));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityPlate.class, new GOTRenderPlate());
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityPlowcart.class, new GOTRenderPlowcart());
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityPortal.class, new GOTRenderPortal());
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityRabbit.class, new GOTRenderRabbit());
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityRedScorpion.class, new GOTRenderRedScorpion());
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityRhino.class, new GOTRenderRhino());
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityScorpion.class, new GOTRenderScorpion());
		RenderingRegistry.registerEntityRenderingHandler(GOTEntitySmokeRing.class, new GOTRenderSmokeRing());
		RenderingRegistry.registerEntityRenderingHandler(GOTEntitySnowBear.class, new GOTRenderSnowBear());
		RenderingRegistry.registerEntityRenderingHandler(GOTEntitySpear.class, new GOTRenderSpear());
		RenderingRegistry.registerEntityRenderingHandler(GOTEntitySwan.class, new GOTRenderSwan());
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityTermite.class, new GOTRenderTermite());
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityTheonGreyjoy.Normal.class, new GOTRenderTheonGreyjoy.Normal());
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityTheonGreyjoy.Tormented.class, new GOTRenderTheonGreyjoy.Tormented());
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityThrowingAxe.class, new GOTRenderThrowingAxe());
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityThrownRock.class, new GOTRenderThrownRock());
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityThrownTermite.class, new RenderSnowball(GOTRegistry.termite));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityTraderRespawn.class, new GOTRenderTraderRespawn());
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityTyrionLannister.class, new GOTRenderTyrionLannister());
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityUlthosSpider.class, new GOTRenderGiantSpider());
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityShadowcat.class, new GOTRenderShadowcat());
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityWalrus.class, new GOTRenderWalrus());
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityWhiteOryx.class, new GOTRenderWhiteOryx());
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityWightGiant.class, new GOTRenderGiant("ice"));
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityWildBoar.class, new GOTRenderWildBoar());
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityWoolyRhino.class, new GOTRenderWoolyRhino());
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityWyvern.class, new GOTRenderWyvern());
		RenderingRegistry.registerEntityRenderingHandler(GOTEntityZebra.class, new GOTRenderZebra());
	}
}
