package got.common.database;

import got.common.entity.animal.*;
import got.common.entity.essos.asshai.*;
import got.common.entity.essos.braavos.*;
import got.common.entity.essos.dothraki.*;
import got.common.entity.essos.ghiscar.*;
import got.common.entity.essos.gold.*;
import got.common.entity.essos.ibben.*;
import got.common.entity.essos.jogos.*;
import got.common.entity.essos.lhazar.*;
import got.common.entity.essos.lorath.*;
import got.common.entity.essos.lys.*;
import got.common.entity.essos.myr.*;
import got.common.entity.essos.norvos.*;
import got.common.entity.essos.pentos.*;
import got.common.entity.essos.qarth.*;
import got.common.entity.essos.qohor.*;
import got.common.entity.essos.tyrosh.*;
import got.common.entity.essos.volantis.*;
import got.common.entity.essos.yiti.*;
import got.common.entity.other.*;
import got.common.entity.sothoryos.sothoryos.*;
import got.common.entity.sothoryos.summer.*;
import got.common.entity.westeros.arryn.*;
import got.common.entity.westeros.crownlands.*;
import got.common.entity.westeros.dorne.*;
import got.common.entity.westeros.dragonstone.*;
import got.common.entity.westeros.gift.*;
import got.common.entity.westeros.hillmen.*;
import got.common.entity.westeros.ironborn.*;
import got.common.entity.westeros.north.*;
import got.common.entity.westeros.north.hillmen.*;
import got.common.entity.westeros.reach.*;
import got.common.entity.westeros.riverlands.*;
import got.common.entity.westeros.stormlands.*;
import got.common.entity.westeros.targaryen.*;
import got.common.entity.westeros.westerlands.*;
import got.common.entity.westeros.wildling.*;
import got.common.entity.westeros.wildling.thenn.*;

public class GOTUnitTradeEntries {
	public static GOTUnitTradeEntries YITI = new GOTUnitTradeEntries(50.0f, new GOTUnitTradeEntry(GOTEntityYiTiLevyman.class, 5, 5.0f), new GOTUnitTradeEntry(GOTEntityYiTiWarrior.class, 10, 10.0f), new GOTUnitTradeEntry(GOTEntityYiTiArcher.class, 15, 15.0f), new GOTUnitTradeEntry(GOTEntityYiTiSamurai.class, 20, 20.0f).setPledgeExclusive(), new GOTUnitTradeEntry(GOTEntityYiTiFireThrower.class, 20, 20.0f).setPledgeExclusive(), new GOTUnitTradeEntry(GOTEntityYiTiBombardier.class, 30, 30.0f).setPledgeExclusive(), new GOTUnitTradeEntry(GOTEntityYiTiWarrior.class, GOTEntityHorse.class, "Rider", 20, 20.0f), new GOTUnitTradeEntry(GOTEntityYiTiSamurai.class, GOTEntityHorse.class, "Rider", 30, 30.0f).setMountArmor(GOTRegistry.yitiHorseArmor).setPledgeExclusive(), new GOTUnitTradeEntry(GOTEntityYiTiBannerBearer.class, 20, 20.0f), new GOTUnitTradeEntry(GOTEntityYiTiBannerBearer.class, GOTEntityHorse.class, "Rider", 20, 30.0f).setMountArmor(GOTRegistry.yitiHorseArmor));
	public static GOTUnitTradeEntries KINGSGUARD = new GOTUnitTradeEntries(50.0f, new GOTUnitTradeEntry(GOTEntityKingsguard.class, 25, 0.0f));
	public static GOTUnitTradeEntries ARRYN = new GOTUnitTradeEntries(50.0f, new GOTUnitTradeEntry(GOTEntityArrynLevyman.class, 5, 5.0f), new GOTUnitTradeEntry(GOTEntityArrynLevymanArcher.class, 10, 10.0f), new GOTUnitTradeEntry(GOTEntityArrynLevyman.class, GOTEntityHorse.class, "Rider", 15, 15.0f), new GOTUnitTradeEntry(GOTEntityArrynSoldier.class, 10, 10.0f), new GOTUnitTradeEntry(GOTEntityArrynSoldierArcher.class, 15, 15.0f), new GOTUnitTradeEntry(GOTEntityArrynSoldier.class, GOTEntityHorse.class, "Rider", 20, 20.0f).setMountArmor(GOTRegistry.westerosHorseArmor), new GOTUnitTradeEntry(GOTEntityArrynBannerBearer.class, 10, 20.0f), new GOTUnitTradeEntry(GOTEntityArrynBannerBearer.class, GOTEntityHorse.class, "Rider", 20, 30.0f).setMountArmor(GOTRegistry.westerosHorseArmor), new GOTUnitTradeEntry(GOTEntityArrynGuard.class, 10, 20.0f));
	public static GOTUnitTradeEntries ARRYN_FARMER = new GOTUnitTradeEntries(0.0f, new GOTUnitTradeEntry(GOTEntityArrynFarmhand.class, 10, 10.0f).setTask(GOTHiredNPCInfo.Task.FARMER));
	public static GOTUnitTradeEntries ASSHAI = new GOTUnitTradeEntries(50.0f, new GOTUnitTradeEntry(GOTEntityAsshaiGuard.class, 5, 5.0f), new GOTUnitTradeEntry(GOTEntityAsshaiSpherebinder.class, 25, 10.0f).setPledgeExclusive(), new GOTUnitTradeEntry(GOTEntityAsshaiShadowbinder.class, 50, 10.0f).setPledgeExclusive());
	public static GOTUnitTradeEntries BRAAVOS = new GOTUnitTradeEntries(50.0f, new GOTUnitTradeEntry(GOTEntityBraavosWarrior.class, 10, 10.0f), new GOTUnitTradeEntry(GOTEntityBraavosWarrior.class, GOTEntityHorse.class, "Rider", 15, 15.0f).setMountArmor(GOTRegistry.essosHorseArmor), new GOTUnitTradeEntry(GOTEntityBraavosArcher.class, 15, 15.0f), new GOTUnitTradeEntry(GOTEntityBraavosLegionary.class, 20, 20.0f), new GOTUnitTradeEntry(GOTEntityBraavosLegionary.class, GOTEntityHorse.class, "Rider", 25, 25.0f).setMountArmor(GOTRegistry.essosHorseArmor), new GOTUnitTradeEntry(GOTEntityBraavosBannerBearer.class, 20, 30.0f), new GOTUnitTradeEntry(GOTEntityBraavosBannerBearer.class, GOTEntityHorse.class, "Rider", 30, 30.0f).setMountArmor(GOTRegistry.essosHorseArmor));
	public static GOTUnitTradeEntries CROWNLANDS = new GOTUnitTradeEntries(50.0f, new GOTUnitTradeEntry(GOTEntityCrownlandsLevyman.class, 5, 5.0f), new GOTUnitTradeEntry(GOTEntityCrownlandsLevymanArcher.class, 10, 10.0f), new GOTUnitTradeEntry(GOTEntityCrownlandsLevyman.class, GOTEntityHorse.class, "Rider", 15, 15.0f), new GOTUnitTradeEntry(GOTEntityCrownlandsBannerBearer.class, 10, 20.0f), new GOTUnitTradeEntry(GOTEntityCrownlandsBannerBearer.class, GOTEntityHorse.class, "Rider", 20, 30.0f).setMountArmor(GOTRegistry.westerosHorseArmor), new GOTUnitTradeEntry(GOTEntityCrownlandsGuard.class, 10, 20.0f));
	public static GOTUnitTradeEntries CROWNLANDS_FARMER = new GOTUnitTradeEntries(0.0f, new GOTUnitTradeEntry(GOTEntityCrownlandsFarmhand.class, 10, 10.0f).setTask(GOTHiredNPCInfo.Task.FARMER));
	public static GOTUnitTradeEntries CROWNLANDS_GUARDIAN = new GOTUnitTradeEntries(50.0f, new GOTUnitTradeEntry(GOTEntityCrownlandsGuard.class, 10, 20.0f));
	public static GOTUnitTradeEntries DORNE = new GOTUnitTradeEntries(50.0f, new GOTUnitTradeEntry(GOTEntityDorneLevyman.class, 5, 5.0f), new GOTUnitTradeEntry(GOTEntityDorneLevymanArcher.class, 10, 10.0f), new GOTUnitTradeEntry(GOTEntityDorneLevyman.class, GOTEntityHorse.class, "Rider", 15, 15.0f), new GOTUnitTradeEntry(GOTEntityDorneSoldier.class, 10, 10.0f), new GOTUnitTradeEntry(GOTEntityDorneSoldierArcher.class, 15, 15.0f), new GOTUnitTradeEntry(GOTEntityDorneSoldier.class, GOTEntityHorse.class, "Rider", 20, 20.0f).setMountArmor(GOTRegistry.westerosHorseArmor), new GOTUnitTradeEntry(GOTEntityDorneBannerBearer.class, 10, 20.0f), new GOTUnitTradeEntry(GOTEntityDorneBannerBearer.class, GOTEntityHorse.class, "Rider", 20, 30.0f).setMountArmor(GOTRegistry.westerosHorseArmor));
	public static GOTUnitTradeEntries DORNE_FARMER = new GOTUnitTradeEntries(0.0f, new GOTUnitTradeEntry(GOTEntityDorneFarmhand.class, 10, 10.0f).setTask(GOTHiredNPCInfo.Task.FARMER));
	public static GOTUnitTradeEntries DOTHRAKI = new GOTUnitTradeEntries(50.0f, new GOTUnitTradeEntry(GOTEntityDothraki.class, GOTEntityHorse.class, "Rider", 10, 0.0f), new GOTUnitTradeEntry(GOTEntityDothrakiArcher.class, GOTEntityHorse.class, "Rider", 20, 0.0f));
	public static GOTUnitTradeEntries DRAGONSTONE = new GOTUnitTradeEntries(50.0f, new GOTUnitTradeEntry(GOTEntityDragonstoneLevyman.class, 5, 5.0f), new GOTUnitTradeEntry(GOTEntityDragonstoneLevymanArcher.class, 10, 10.0f), new GOTUnitTradeEntry(GOTEntityDragonstoneLevyman.class, GOTEntityHorse.class, "Rider", 15, 15.0f), new GOTUnitTradeEntry(GOTEntityDragonstoneSoldier.class, 10, 10.0f), new GOTUnitTradeEntry(GOTEntityDragonstoneSoldierArcher.class, 15, 15.0f), new GOTUnitTradeEntry(GOTEntityDragonstoneSoldier.class, GOTEntityHorse.class, "Rider", 20, 20.0f).setMountArmor(GOTRegistry.westerosHorseArmor), new GOTUnitTradeEntry(GOTEntityDragonstoneBannerBearer.class, 10, 20.0f), new GOTUnitTradeEntry(GOTEntityDragonstoneBannerBearer.class, GOTEntityHorse.class, "Rider", 20, 30.0f).setMountArmor(GOTRegistry.westerosHorseArmor));
	public static GOTUnitTradeEntries DRAGONSTONE_FARMER = new GOTUnitTradeEntries(0.0f, new GOTUnitTradeEntry(GOTEntityDragonstoneFarmhand.class, 10, 10.0f).setTask(GOTHiredNPCInfo.Task.FARMER));
	public static GOTUnitTradeEntries GHISCAR = new GOTUnitTradeEntries(50.0f, new GOTUnitTradeEntry(GOTEntityGhiscarLevyman.class, 10, 10.0f), new GOTUnitTradeEntry(GOTEntityGhiscarArcher.class, 15, 15.0f), new GOTUnitTradeEntry(GOTEntityGhiscarBannerBearer.class, 20, 30.0f));
	public static GOTUnitTradeEntries GHISCAR_UNSULLIED = new GOTUnitTradeEntries(50.0f, new GOTUnitTradeEntry(GOTEntityGhiscarUnsullied.class, 50, 50.0f));
	public static GOTUnitTradeEntries GHISCAR_CORSAIR = new GOTUnitTradeEntries(50.0f, new GOTUnitTradeEntry(GOTEntityGhiscarLevyman.class, 10, 10.0f), new GOTUnitTradeEntry(GOTEntityGhiscarArcher.class, 15, 15.0f), new GOTUnitTradeEntry(GOTEntityGhiscarCorsair.class, 20, 20.0f), new GOTUnitTradeEntry(GOTEntityGhiscarBannerBearer.class, 20, 30.0f));
	public static GOTUnitTradeEntries GHISCAR_SLAVER = new GOTUnitTradeEntries(0.0f, new GOTUnitTradeEntry(GOTEntityGhiscarSlave.class, 10, 10.0f).setTask(GOTHiredNPCInfo.Task.FARMER));
	public static GOTUnitTradeEntries GIFT = new GOTUnitTradeEntries(50.0f, new GOTUnitTradeEntry(GOTEntityGiftGuard.class, 10, 0.0f).setPledgeExclusive(), new GOTUnitTradeEntry(GOTEntityGiftBannerBearer.class, 15, 10.0f).setPledgeExclusive());
	public static GOTUnitTradeEntries GOLD = new GOTUnitTradeEntries(0.0f, new GOTUnitTradeEntry(GOTEntityGoldenWarrior.class, 10, 0.0f), new GOTUnitTradeEntry(GOTEntityGoldenSpearman.class, 10, 0.0f), new GOTUnitTradeEntry(GOTEntityGoldenBannerBearer.class, 15, 0.0f));
	public static GOTUnitTradeEntries HILLMEN = new GOTUnitTradeEntries(50.0f, new GOTUnitTradeEntry(GOTEntityHillman.class, 10, 10.0f), new GOTUnitTradeEntry(GOTEntityHillmanArcher.class, 15, 15.0f), new GOTUnitTradeEntry(GOTEntityHillmanAxeThrower.class, 15, 15.0f), new GOTUnitTradeEntry(GOTEntityHillmanBannerBearer.class, 15, 20.0f), new GOTUnitTradeEntry(GOTEntityHillmanBerserker.class, 20, 20.0f).setPledgeExclusive());
	public static GOTUnitTradeEntries IBBEN = new GOTUnitTradeEntries(50.0f, new GOTUnitTradeEntry(GOTEntityIbbenWarrior.class, 10, 10.0f), new GOTUnitTradeEntry(GOTEntityIbbenArcher.class, 15, 15.0f), new GOTUnitTradeEntry(GOTEntityIbbenAxeThrower.class, 15, 15.0f));
	public static GOTUnitTradeEntries IBBEN_FARMER = new GOTUnitTradeEntries(0.0f, new GOTUnitTradeEntry(GOTEntityIbbenFarmhand.class, 10, 10.0f).setTask(GOTHiredNPCInfo.Task.FARMER));
	public static GOTUnitTradeEntries IRONBORN = new GOTUnitTradeEntries(50.0f, new GOTUnitTradeEntry(GOTEntityIronbornLevyman.class, 5, 5.0f), new GOTUnitTradeEntry(GOTEntityIronbornLevymanArcher.class, 10, 10.0f), new GOTUnitTradeEntry(GOTEntityIronbornSoldier.class, 10, 10.0f), new GOTUnitTradeEntry(GOTEntityIronbornCorsair.class, 10, 15.0f), new GOTUnitTradeEntry(GOTEntityIronbornSoldierArcher.class, 15, 15.0f), new GOTUnitTradeEntry(GOTEntityIronbornBannerBearer.class, 10, 20.0f));
	public static GOTUnitTradeEntries IRONBORN_FARMER = new GOTUnitTradeEntries(0.0f, new GOTUnitTradeEntry(GOTEntityIronbornFarmhand.class, 10, 10.0f).setTask(GOTHiredNPCInfo.Task.FARMER));
	public static GOTUnitTradeEntries JOGOS = new GOTUnitTradeEntries(50.0f, new GOTUnitTradeEntry(GOTEntityJogos.class, GOTEntityZebra.class, "Rider", 10, 0.0f), new GOTUnitTradeEntry(GOTEntityJogosArcher.class, GOTEntityZebra.class, "Rider", 20, 0.0f));
	public static GOTUnitTradeEntries LHAZAR = new GOTUnitTradeEntries(50.0f, new GOTUnitTradeEntry(GOTEntityLhazarWarrior.class, 10, 10.0f), new GOTUnitTradeEntry(GOTEntityLhazarArcher.class, 15, 15.0f), new GOTUnitTradeEntry(GOTEntityLhazarWarrior.class, GOTEntityZebra.class, "Rider", 15, 15.0f), new GOTUnitTradeEntry(GOTEntityLhazarArcher.class, GOTEntityZebra.class, "Rider", 20, 20.0f), new GOTUnitTradeEntry(GOTEntityLhazarBannerBearer.class, 15, 15.0f));
	public static GOTUnitTradeEntries LORATH = new GOTUnitTradeEntries(50.0f, new GOTUnitTradeEntry(GOTEntityLorathWarrior.class, 10, 10.0f), new GOTUnitTradeEntry(GOTEntityLorathWarrior.class, GOTEntityHorse.class, "Rider", 15, 15.0f).setMountArmor(GOTRegistry.essosHorseArmor), new GOTUnitTradeEntry(GOTEntityLorathArcher.class, 15, 15.0f), new GOTUnitTradeEntry(GOTEntityLorathLegionary.class, 20, 20.0f), new GOTUnitTradeEntry(GOTEntityLorathLegionary.class, GOTEntityHorse.class, "Rider", 25, 25.0f).setMountArmor(GOTRegistry.essosHorseArmor), new GOTUnitTradeEntry(GOTEntityLorathBannerBearer.class, 20, 30.0f), new GOTUnitTradeEntry(GOTEntityLorathBannerBearer.class, GOTEntityHorse.class, "Rider", 30, 30.0f).setMountArmor(GOTRegistry.essosHorseArmor));
	public static GOTUnitTradeEntries LYS = new GOTUnitTradeEntries(50.0f, new GOTUnitTradeEntry(GOTEntityLysWarrior.class, 10, 10.0f), new GOTUnitTradeEntry(GOTEntityLysWarrior.class, GOTEntityHorse.class, "Rider", 15, 15.0f).setMountArmor(GOTRegistry.essosHorseArmor), new GOTUnitTradeEntry(GOTEntityLysArcher.class, 15, 15.0f), new GOTUnitTradeEntry(GOTEntityLysLegionary.class, 20, 20.0f), new GOTUnitTradeEntry(GOTEntityLysLegionary.class, GOTEntityHorse.class, "Rider", 25, 25.0f).setMountArmor(GOTRegistry.essosHorseArmor), new GOTUnitTradeEntry(GOTEntityLysBannerBearer.class, 20, 30.0f), new GOTUnitTradeEntry(GOTEntityLysBannerBearer.class, GOTEntityHorse.class, "Rider", 30, 30.0f).setMountArmor(GOTRegistry.essosHorseArmor));
	public static GOTUnitTradeEntries LYS_SLAVER = new GOTUnitTradeEntries(0.0f, new GOTUnitTradeEntry(GOTEntityLysSlave.class, 10, 10.0f).setTask(GOTHiredNPCInfo.Task.FARMER));
	public static GOTUnitTradeEntries MYR = new GOTUnitTradeEntries(50.0f, new GOTUnitTradeEntry(GOTEntityMyrWarrior.class, 10, 10.0f), new GOTUnitTradeEntry(GOTEntityMyrWarrior.class, GOTEntityHorse.class, "Rider", 15, 15.0f).setMountArmor(GOTRegistry.essosHorseArmor), new GOTUnitTradeEntry(GOTEntityMyrArcher.class, 15, 15.0f), new GOTUnitTradeEntry(GOTEntityMyrLegionary.class, 20, 20.0f), new GOTUnitTradeEntry(GOTEntityMyrLegionary.class, GOTEntityHorse.class, "Rider", 25, 25.0f).setMountArmor(GOTRegistry.essosHorseArmor), new GOTUnitTradeEntry(GOTEntityMyrBannerBearer.class, 20, 30.0f), new GOTUnitTradeEntry(GOTEntityMyrBannerBearer.class, GOTEntityHorse.class, "Rider", 30, 30.0f).setMountArmor(GOTRegistry.essosHorseArmor));
	public static GOTUnitTradeEntries MYR_SLAVER = new GOTUnitTradeEntries(0.0f, new GOTUnitTradeEntry(GOTEntityMyrSlave.class, 10, 10.0f).setTask(GOTHiredNPCInfo.Task.FARMER));
	public static GOTUnitTradeEntries NORTH = new GOTUnitTradeEntries(50.0f, new GOTUnitTradeEntry(GOTEntityNorthLevyman.class, 5, 5.0f), new GOTUnitTradeEntry(GOTEntityNorthLevymanArcher.class, 10, 10.0f), new GOTUnitTradeEntry(GOTEntityNorthLevyman.class, GOTEntityHorse.class, "Rider", 15, 15.0f), new GOTUnitTradeEntry(GOTEntityNorthSoldier.class, 10, 10.0f), new GOTUnitTradeEntry(GOTEntityNorthSoldierArcher.class, 15, 15.0f), new GOTUnitTradeEntry(GOTEntityNorthSoldier.class, GOTEntityHorse.class, "Rider", 20, 20.0f).setMountArmor(GOTRegistry.westerosHorseArmor), new GOTUnitTradeEntry(GOTEntityNorthBannerBearer.class, 10, 20.0f), new GOTUnitTradeEntry(GOTEntityNorthGuard.class, 10, 20.0f));
	public static GOTUnitTradeEntries NORTH_FARMER = new GOTUnitTradeEntries(0.0f, new GOTUnitTradeEntry(GOTEntityNorthFarmhand.class, 10, 10.0f).setTask(GOTHiredNPCInfo.Task.FARMER));
	public static GOTUnitTradeEntries NORTH_HILLMEN = new GOTUnitTradeEntries(50.0f, new GOTUnitTradeEntry(GOTEntityNorthHillman.class, 5, 5.0f), new GOTUnitTradeEntry(GOTEntityNorthHillmanWarrior.class, 10, 10.0f), new GOTUnitTradeEntry(GOTEntityNorthHillmanArcher.class, 15, 15.0f), new GOTUnitTradeEntry(GOTEntityNorthHillmanAxeThrower.class, 15, 15.0f), new GOTUnitTradeEntry(GOTEntityNorthHillmanBannerBearer.class, 15, 20.0f), new GOTUnitTradeEntry(GOTEntityNorthHillman.class, GOTEntityWoolyRhino.class, "Rider", 30, 30.0f).setPledgeExclusive());
	public static GOTUnitTradeEntries NORVOS = new GOTUnitTradeEntries(50.0f, new GOTUnitTradeEntry(GOTEntityNorvosWarrior.class, 10, 10.0f), new GOTUnitTradeEntry(GOTEntityNorvosWarrior.class, GOTEntityHorse.class, "Rider", 15, 15.0f).setMountArmor(GOTRegistry.essosHorseArmor), new GOTUnitTradeEntry(GOTEntityNorvosArcher.class, 15, 15.0f), new GOTUnitTradeEntry(GOTEntityNorvosGuard.class, 20, 20.0f), new GOTUnitTradeEntry(GOTEntityNorvosBannerBearer.class, 20, 30.0f), new GOTUnitTradeEntry(GOTEntityNorvosBannerBearer.class, GOTEntityHorse.class, "Rider", 30, 30.0f).setMountArmor(GOTRegistry.essosHorseArmor));
	public static GOTUnitTradeEntries PENTOS = new GOTUnitTradeEntries(50.0f, new GOTUnitTradeEntry(GOTEntityPentosLevyman.class, 10, 10.0f), new GOTUnitTradeEntry(GOTEntityPentosArcher.class, 15, 15.0f), new GOTUnitTradeEntry(GOTEntityPentosGuard.class, 20, 20.0f), new GOTUnitTradeEntry(GOTEntityPentosBannerBearer.class, 20, 30.0f), new GOTUnitTradeEntry(GOTEntityPentosBannerBearer.class, GOTEntityHorse.class, "Rider", 30, 30.0f).setMountArmor(GOTRegistry.essosHorseArmor));
	public static GOTUnitTradeEntries QARTH = new GOTUnitTradeEntries(50.0f, new GOTUnitTradeEntry(GOTEntityQarthWarrior.class, 10, 10.0f), new GOTUnitTradeEntry(GOTEntityQarthWarrior.class, GOTEntityCamel.class, "Rider", 15, 15.0f), new GOTUnitTradeEntry(GOTEntityQarthArcher.class, 15, 15.0f), new GOTUnitTradeEntry(GOTEntityQarthGuard.class, 20, 20.0f), new GOTUnitTradeEntry(GOTEntityQarthBannerBearer.class, 20, 30.0f), new GOTUnitTradeEntry(GOTEntityQarthBannerBearer.class, GOTEntityCamel.class, "Rider", 30, 30.0f).setMountArmor(GOTRegistry.essosHorseArmor));
	public static GOTUnitTradeEntries QOHOR = new GOTUnitTradeEntries(50.0f, new GOTUnitTradeEntry(GOTEntityQohorLevyman.class, 10, 10.0f), new GOTUnitTradeEntry(GOTEntityQohorArcher.class, 15, 15.0f), new GOTUnitTradeEntry(GOTEntityQohorUnsullied.class, 50, 50.0f), new GOTUnitTradeEntry(GOTEntityQohorGuard.class, 20, 20.0f), new GOTUnitTradeEntry(GOTEntityQohorBannerBearer.class, 20, 30.0f), new GOTUnitTradeEntry(GOTEntityQohorBannerBearer.class, GOTEntityHorse.class, "Rider", 30, 30.0f).setMountArmor(GOTRegistry.essosHorseArmor));
	public static GOTUnitTradeEntries REACH = new GOTUnitTradeEntries(50.0f, new GOTUnitTradeEntry(GOTEntityReachLevyman.class, 5, 5.0f), new GOTUnitTradeEntry(GOTEntityReachLevymanArcher.class, 10, 10.0f), new GOTUnitTradeEntry(GOTEntityReachLevyman.class, GOTEntityHorse.class, "Rider", 15, 15.0f), new GOTUnitTradeEntry(GOTEntityReachSoldier.class, 10, 10.0f), new GOTUnitTradeEntry(GOTEntityReachSoldierArcher.class, 15, 15.0f), new GOTUnitTradeEntry(GOTEntityReachSoldier.class, GOTEntityHorse.class, "Rider", 20, 20.0f).setMountArmor(GOTRegistry.westerosHorseArmor), new GOTUnitTradeEntry(GOTEntityReachBannerBearer.class, 10, 20.0f), new GOTUnitTradeEntry(GOTEntityReachBannerBearer.class, GOTEntityHorse.class, "Rider", 20, 30.0f).setMountArmor(GOTRegistry.westerosHorseArmor), new GOTUnitTradeEntry(GOTEntityReachGuard.class, 10, 20.0f));
	public static GOTUnitTradeEntries REACH_FARMER = new GOTUnitTradeEntries(0.0f, new GOTUnitTradeEntry(GOTEntityReachFarmhand.class, 10, 10.0f).setTask(GOTHiredNPCInfo.Task.FARMER));
	public static GOTUnitTradeEntries RIVERLANDS = new GOTUnitTradeEntries(50.0f, new GOTUnitTradeEntry(GOTEntityRiverlandsLevyman.class, 5, 5.0f), new GOTUnitTradeEntry(GOTEntityRiverlandsLevymanArcher.class, 10, 10.0f), new GOTUnitTradeEntry(GOTEntityRiverlandsLevyman.class, GOTEntityHorse.class, "Rider", 15, 15.0f), new GOTUnitTradeEntry(GOTEntityRiverlandsSoldier.class, 10, 10.0f), new GOTUnitTradeEntry(GOTEntityRiverlandsSoldierArcher.class, 15, 15.0f), new GOTUnitTradeEntry(GOTEntityRiverlandsSoldier.class, GOTEntityHorse.class, "Rider", 20, 20.0f).setMountArmor(GOTRegistry.westerosHorseArmor), new GOTUnitTradeEntry(GOTEntityRiverlandsBannerBearer.class, 10, 20.0f), new GOTUnitTradeEntry(GOTEntityRiverlandsBannerBearer.class, GOTEntityHorse.class, "Rider", 20, 30.0f).setMountArmor(GOTRegistry.westerosHorseArmor));
	public static GOTUnitTradeEntries RIVERLANDS_FARMER = new GOTUnitTradeEntries(0.0f, new GOTUnitTradeEntry(GOTEntityRiverlandsFarmhand.class, 10, 10.0f).setTask(GOTHiredNPCInfo.Task.FARMER));
	public static GOTUnitTradeEntries SOTHORYOS = new GOTUnitTradeEntries(50.0f, new GOTUnitTradeEntry(GOTEntitySothoryosWarrior.class, 10, 10.0f), new GOTUnitTradeEntry(GOTEntitySothoryosBlowgunner.class, 15, 15.0f), new GOTUnitTradeEntry(GOTEntitySothoryosBannerBearer.class, 15, 15.0f));
	public static GOTUnitTradeEntries SOTHORYOS_FARMER = new GOTUnitTradeEntries(0.0f, new GOTUnitTradeEntry(GOTEntitySothoryosFarmhand.class, 10, 10.0f).setTask(GOTHiredNPCInfo.Task.FARMER));
	public static GOTUnitTradeEntries STORMLANDS = new GOTUnitTradeEntries(50.0f, new GOTUnitTradeEntry(GOTEntityStormlandsLevyman.class, 5, 5.0f), new GOTUnitTradeEntry(GOTEntityStormlandsLevymanArcher.class, 10, 10.0f), new GOTUnitTradeEntry(GOTEntityStormlandsLevyman.class, GOTEntityHorse.class, "Rider", 15, 15.0f), new GOTUnitTradeEntry(GOTEntityStormlandsSoldier.class, 10, 10.0f), new GOTUnitTradeEntry(GOTEntityStormlandsSoldierArcher.class, 15, 15.0f), new GOTUnitTradeEntry(GOTEntityStormlandsSoldier.class, GOTEntityHorse.class, "Rider", 20, 20.0f).setMountArmor(GOTRegistry.westerosHorseArmor), new GOTUnitTradeEntry(GOTEntityStormlandsBannerBearer.class, 20, 20.0f), new GOTUnitTradeEntry(GOTEntityStormlandsBannerBearer.class, GOTEntityHorse.class, "Rider", 20, 30.0f).setMountArmor(GOTRegistry.westerosHorseArmor));
	public static GOTUnitTradeEntries STORMLANDS_FARMER = new GOTUnitTradeEntries(0.0f, new GOTUnitTradeEntry(GOTEntityStormlandsFarmhand.class, 10, 10.0f).setTask(GOTHiredNPCInfo.Task.FARMER));
	public static GOTUnitTradeEntries SUMMER = new GOTUnitTradeEntries(50.0f, new GOTUnitTradeEntry(GOTEntitySummerWarrior.class, 5, 5.0f), new GOTUnitTradeEntry(GOTEntitySummerArcher.class, 10, 10.0f), new GOTUnitTradeEntry(GOTEntitySummerWarrior.class, GOTEntityHorse.class, "Rider", 15, 15.0f), new GOTUnitTradeEntry(GOTEntitySummerBannerBearer.class, 10, 20.0f));
	public static GOTUnitTradeEntries SUMMER_FARMER = new GOTUnitTradeEntries(0.0f, new GOTUnitTradeEntry(GOTEntitySummerFarmhand.class, 10, 10.0f).setTask(GOTHiredNPCInfo.Task.FARMER));
	public static GOTUnitTradeEntries TARGARYEN = new GOTUnitTradeEntries(50.0f, new GOTUnitTradeEntry(GOTEntityTargaryenLevyman.class, 5, 5.0f), new GOTUnitTradeEntry(GOTEntityTargaryenLevymanArcher.class, 10, 10.0f), new GOTUnitTradeEntry(GOTEntityTargaryenLevyman.class, GOTEntityHorse.class, "Rider", 15, 15.0f), new GOTUnitTradeEntry(GOTEntityTargaryenSoldier.class, 10, 10.0f), new GOTUnitTradeEntry(GOTEntityTargaryenSoldierArcher.class, 15, 15.0f), new GOTUnitTradeEntry(GOTEntityTargaryenSoldier.class, GOTEntityHorse.class, "Rider", 20, 20.0f).setMountArmor(GOTRegistry.westerosHorseArmor), new GOTUnitTradeEntry(GOTEntityTargaryenBannerBearer.class, 10, 20.0f), new GOTUnitTradeEntry(GOTEntityTargaryenBannerBearer.class, GOTEntityHorse.class, "Rider", 20, 30.0f).setMountArmor(GOTRegistry.westerosHorseArmor));
	public static GOTUnitTradeEntries TARGARYEN_FARMER = new GOTUnitTradeEntries(0.0f, new GOTUnitTradeEntry(GOTEntityTargaryenFarmhand.class, 10, 10.0f).setTask(GOTHiredNPCInfo.Task.FARMER));
	public static GOTUnitTradeEntries THENN = new GOTUnitTradeEntries(50.0f, new GOTUnitTradeEntry(GOTEntityThenn.class, 10, 10.0f), new GOTUnitTradeEntry(GOTEntityThennArcher.class, 15, 15.0f), new GOTUnitTradeEntry(GOTEntityThennAxeThrower.class, 15, 15.0f), new GOTUnitTradeEntry(GOTEntityThennBannerBearer.class, 15, 20.0f), new GOTUnitTradeEntry(GOTEntityThennBerserker.class, 30, 30.0f).setPledgeExclusive(), new GOTUnitTradeEntry(GOTEntityGiant.class, 30, 30.0f).setPledgeExclusive());
	public static GOTUnitTradeEntries TYROSH = new GOTUnitTradeEntries(50.0f, new GOTUnitTradeEntry(GOTEntityTyroshWarrior.class, 10, 10.0f), new GOTUnitTradeEntry(GOTEntityTyroshWarrior.class, GOTEntityHorse.class, "Rider", 15, 15.0f).setMountArmor(GOTRegistry.essosHorseArmor), new GOTUnitTradeEntry(GOTEntityTyroshArcher.class, 15, 15.0f), new GOTUnitTradeEntry(GOTEntityTyroshLegionary.class, 20, 20.0f), new GOTUnitTradeEntry(GOTEntityTyroshLegionary.class, GOTEntityHorse.class, "Rider", 25, 25.0f).setMountArmor(GOTRegistry.essosHorseArmor), new GOTUnitTradeEntry(GOTEntityTyroshBannerBearer.class, 20, 30.0f), new GOTUnitTradeEntry(GOTEntityTyroshBannerBearer.class, GOTEntityHorse.class, "Rider", 30, 30.0f).setMountArmor(GOTRegistry.essosHorseArmor));
	public static GOTUnitTradeEntries TYROSH_SLAVER = new GOTUnitTradeEntries(0.0f, new GOTUnitTradeEntry(GOTEntityTyroshSlave.class, 10, 10.0f).setTask(GOTHiredNPCInfo.Task.FARMER));
	public static GOTUnitTradeEntries VOLANTIS = new GOTUnitTradeEntries(50.0f, new GOTUnitTradeEntry(GOTEntityVolantisWarrior.class, 10, 10.0f), new GOTUnitTradeEntry(GOTEntityVolantisWarrior.class, GOTEntityHorse.class, "Rider", 15, 15.0f).setMountArmor(GOTRegistry.essosHorseArmor), new GOTUnitTradeEntry(GOTEntityVolantisArcher.class, 15, 15.0f), new GOTUnitTradeEntry(GOTEntityVolantisLegionary.class, 20, 20.0f), new GOTUnitTradeEntry(GOTEntityVolantisLegionary.class, GOTEntityHorse.class, "Rider", 25, 25.0f).setMountArmor(GOTRegistry.essosHorseArmor), new GOTUnitTradeEntry(GOTEntityVolantisBannerBearer.class, 20, 30.0f), new GOTUnitTradeEntry(GOTEntityVolantisBannerBearer.class, GOTEntityHorse.class, "Rider", 30, 30.0f).setMountArmor(GOTRegistry.essosHorseArmor));
	public static GOTUnitTradeEntries VOLANTIS_SLAVER = new GOTUnitTradeEntries(0.0f, new GOTUnitTradeEntry(GOTEntityVolantisSlave.class, 10, 10.0f).setTask(GOTHiredNPCInfo.Task.FARMER));
	public static GOTUnitTradeEntries WALDER = new GOTUnitTradeEntries(0.0f, new GOTUnitTradeEntry(GOTEntityRiverlandsLevyman.class, 10, 0.0f), new GOTUnitTradeEntry(GOTEntityRiverlandsLevymanArcher.class, 20, 0.0f), new GOTUnitTradeEntry(GOTEntityRiverlandsLevyman.class, GOTEntityHorse.class, "Rider", 30, 0.0f), new GOTUnitTradeEntry(GOTEntityRiverlandsSoldier.class, 20, 0.0f), new GOTUnitTradeEntry(GOTEntityRiverlandsSoldierArcher.class, 30, 0f), new GOTUnitTradeEntry(GOTEntityRiverlandsSoldier.class, GOTEntityHorse.class, "Rider", 40, 0.0f).setMountArmor(GOTRegistry.westerosHorseArmor), new GOTUnitTradeEntry(GOTEntityRiverlandsBannerBearer.class, 20, 0.0f), new GOTUnitTradeEntry(GOTEntityRiverlandsBannerBearer.class, GOTEntityHorse.class, "Rider", 40, 0.0f).setMountArmor(GOTRegistry.westerosHorseArmor));
	public static GOTUnitTradeEntries WESTERLANDS = new GOTUnitTradeEntries(50.0f, new GOTUnitTradeEntry(GOTEntityWesterlandsLevyman.class, 5, 5.0f), new GOTUnitTradeEntry(GOTEntityWesterlandsLevymanArcher.class, 10, 10.0f), new GOTUnitTradeEntry(GOTEntityWesterlandsLevyman.class, GOTEntityHorse.class, "Rider", 15, 15.0f), new GOTUnitTradeEntry(GOTEntityWesterlandsSoldier.class, 10, 10.0f), new GOTUnitTradeEntry(GOTEntityWesterlandsSoldierArcher.class, 15, 15.0f), new GOTUnitTradeEntry(GOTEntityWesterlandsSoldier.class, GOTEntityHorse.class, "Rider", 20, 20.0f).setMountArmor(GOTRegistry.westerosHorseArmor), new GOTUnitTradeEntry(GOTEntityWesterlandsBannerBearer.class, 10, 20.0f), new GOTUnitTradeEntry(GOTEntityWesterlandsBannerBearer.class, GOTEntityHorse.class, "Rider", 20, 30.0f).setMountArmor(GOTRegistry.westerosHorseArmor), new GOTUnitTradeEntry(GOTEntityWesterlandsGuard.class, 10, 20.0f));
	public static GOTUnitTradeEntries WESTERLANDS_FARMER = new GOTUnitTradeEntries(0.0f, new GOTUnitTradeEntry(GOTEntityWesterlandsFarmhand.class, 10, 10.0f).setTask(GOTHiredNPCInfo.Task.FARMER));
	public static GOTUnitTradeEntries WILDLING = new GOTUnitTradeEntries(50.0f, new GOTUnitTradeEntry(GOTEntityWildling.class, 10, 10.0f), new GOTUnitTradeEntry(GOTEntityWildlingArcher.class, 15, 15.0f), new GOTUnitTradeEntry(GOTEntityWildlingAxeThrower.class, 15, 15.0f), new GOTUnitTradeEntry(GOTEntityWildlingBannerBearer.class, 15, 20.0f), new GOTUnitTradeEntry(GOTEntityGiant.class, 50, 10.0f).setPledgeExclusive());
	public static GOTUnitTradeEntries YITI_FARMER = new GOTUnitTradeEntries(0.0f, new GOTUnitTradeEntry(GOTEntityYiTiFarmhand.class, 10, 10.0f).setTask(GOTHiredNPCInfo.Task.FARMER));
	public static int lhazar_MERCENARY_COST = 20;
	public GOTUnitTradeEntry[] tradeEntries;

	public GOTUnitTradeEntries(float baseAlignment, GOTUnitTradeEntry... trades) {
		for (GOTUnitTradeEntry trade : tradeEntries = trades) {
			trade.alignmentRequired += baseAlignment;
			if ((trade.alignmentRequired >= 0.0f)) {
				continue;
			}
			throw new IllegalArgumentException("Units cannot require negative alignment!");
		}
	}
}
